# Base variables
project_name="object-shape"
attachment="ccn8"
base_folder="experiments/${attachment}"
dataset="new_tetronimoes"
N=64
num_classes=6
c_mid=16
batch_size=64
min_epochs=250
max_epochs=300
lr=1.0e-3
seed=6
min_iters=0
max_iters=100
dt=0.1
hidden_channels=2
rnn_kernel=3
kernel_init='op' # options: 'vanilla' 'op' 'pk'
cp_path="cp.pt"
save_model=True
num_channels_plot=2 # to plot all, set num_channels_plot to null or the value of hidden_channels
normalize=True
optimizer='adam' # adam, adamw
weight_decay=0.01
cell_type='lstm' # rnn, gru, lstm
num_layers=16 # for baseline
training_patience=302
training_tolerance=0.001